import { SyntaxStyle } from "@opentui/core";
import { COLORS } from "./theme";

export const ALL_SLASH_COMMANDS = [
  "/help",
  "/clear",
  "/compact",
  "/sessions",
  "/memory",
  "/model",
  "/workspace",
  "/skills",
  "/mcp",
  "/tools",
  "/plan",
  "/copy",
  "/undo",
  "/quit",
];

export const LAVA_LAMP_FRAMES = [
  [
    "       _____",
    "      /     \\",
    "      |_____|",
    "      /  _  \\",
    "     /  ( )  \\",
    "    /    `    \\",
    "   /     _     \\",
    "  /     ( )     \\",
    "  \\      )\\     /",
    "   \\    (  )   /",
    "    \\  ,-(   /",
    "     \\/-----\\/",
    "     |       |",
    "     /       \\",
    "    /________\\--._",
    "               .-._)",
    "              (__",
    "                 -`|E",
  ],

  [
    "       _____",
    "      /     \\",
    "      |_____|",
    "      /  _  \\",
    "     /  ( )  \\",
    "    /    `    \\",
    "   /    (_)    \\",
    "  /     ( )     \\",
    "  \\      ))     /",
    "   \\    (  )   /",
    "    \\  ,-(   /",
    "     \\/-----\\/",
    "     |       |",
    "     /       \\",
    "    /________\\--._",
    "               .-._)",
    "              (__",
    "                 -`|E",
  ],

  [
    "       _____",
    "      /     \\",
    "      |_____|",
    "      / (_) \\",
    "     /  `-'  \\",
    "    /    _    \\",
    "   /    ( )    \\",
    "  /      |      \\",
    "  \\     ( )     /",
    "   \\     |     /",
    "    \\   (_)   /",
    "     \\/-----\\/",
    "     |       |",
    "     /       \\",
    "    /________\\--._",
    "               .-._)",
    "              (__",
    "                 -`|E",
  ],

  [
    "       _____",
    "      /     \\",
    "      |_____|",
    "      / .-. \\",
    "     / (   ) \\",
    "    /  `-.-'  \\",
    "   /     |     \\",
    "  /     ( )     \\",
    "  \\      |      /",
    "   \\    ( )    /",
    "    \\   |     /",
    "     \\/-----\\/",
    "     |       |",
    "     /       \\",
    "    /________\\--._",
    "               .-._)",
    "              (__",
    "                 -`|E",
  ],
];

export const syntaxStyle = SyntaxStyle.fromStyles({
  default: { fg: COLORS.white },
  string: { fg: "#A5D6FF" },
  keyword: { fg: "#FF7B72", bold: true },
  comment: { fg: "#666666" },
  function: { fg: "#D2A8FF" },
  number: { fg: "#79C0FF" },
  operator: { fg: "#FF7B72" },
  type: { fg: "#FFA657" },
  variable: { fg: "#FFA657" },
  property: { fg: "#79C0FF" },
  constant: { fg: "#79C0FF" },
  "markup.heading": { fg: "#58A6FF", bold: true },
  "markup.list": { fg: "#FF7B72" },
  "markup.raw": { fg: "#A5D6FF" },
});
