import { SyntaxStyle } from '@opentui/core';
import { COLORS } from './theme';

export const ALL_SLASH_COMMANDS = [
  '/help',
  '/clear',
  '/compact',
  '/sessions',
  '/memory',
  '/model',
  '/gateway',
  '/usage',
  '/workspace',
  '/skills',
  '/mcp',
  '/tools',
  '/subagents',
  '/plan',
  '/sudo',
  '/permissions',
  '/copy',
  '/undo',
  '/quit',
  '/paste-image',
];

export const SLASH_COMMAND_DESCRIPTIONS: Record<string, string> = {
  '/clear': 'new session',
  '/compact': 'shrink context',
  '/copy': 'copy transcript',
  '/gateway': 'configure ai gateway',
  '/help': 'show help',
  '/mcp': 'list mcp',
  '/memory': 'show memory',
  '/model': 'show model',
  '/paste-image': 'paste clipboard image',
  '/permissions': 'show rules',
  '/plan': 'toggle plan',
  '/quit': 'exit app',
  '/sessions': 'switch session',
  '/skills': 'list skills',
  '/subagents': 'list subagents',
  '/sudo': 'allow everything',
  '/tools': 'list tools',
  '/undo': 'undo change',
  '/usage': 'show neuron meter',
  '/workspace': 'show workspace',
};

export const LAVA_LAMP_FRAMES = [
  [
    '       _____',
    '      /     \\',
    '      |_____|',
    '      /  _  \\',
    '     /  ( )  \\',
    '    /    `    \\',
    '   /     _     \\',
    '  /     ( )     \\',
    String.raw`  \      )\     /`,
    String.raw`   \    (  )   /`,
    String.raw`    \  ,-(   /`,
    String.raw`     \/-----\/`,
    '     |       |',
    '     /       \\',
    String.raw`    /________\--._`,
    '               .-._)',
    '              (__',
    '                 -`|E',
  ],

  [
    '       _____',
    '      /     \\',
    '      |_____|',
    '      /  _  \\',
    '     /  ( )  \\',
    '    /    `    \\',
    '   /    (_)    \\',
    '  /     ( )     \\',
    String.raw`  \      ))     /`,
    String.raw`   \    (  )   /`,
    String.raw`    \  ,-(   /`,
    String.raw`     \/-----\/`,
    '     |       |',
    '     /       \\',
    String.raw`    /________\--._`,
    '               .-._)',
    '              (__',
    '                 -`|E',
  ],

  [
    '       _____',
    '      /     \\',
    '      |_____|',
    '      / (_) \\',
    "     /  `-'  \\",
    '    /    _    \\',
    '   /    ( )    \\',
    '  /      |      \\',
    String.raw`  \     ( )     /`,
    String.raw`   \     |     /`,
    String.raw`    \   (_)   /`,
    String.raw`     \/-----\/`,
    '     |       |',
    '     /       \\',
    String.raw`    /________\--._`,
    '               .-._)',
    '              (__',
    '                 -`|E',
  ],

  [
    '       _____',
    '      /     \\',
    '      |_____|',
    '      / .-. \\',
    '     / (   ) \\',
    "    /  `-.-'  \\",
    '   /     |     \\',
    '  /     ( )     \\',
    String.raw`  \      |      /`,
    String.raw`   \    ( )    /`,
    String.raw`    \   |     /`,
    String.raw`     \/-----\/`,
    '     |       |',
    '     /       \\',
    String.raw`    /________\--._`,
    '               .-._)',
    '              (__',
    '                 -`|E',
  ],
];

export const syntaxStyle = SyntaxStyle.fromStyles({
  comment: { fg: '#666666' },
  constant: { fg: '#79C0FF' },
  default: { fg: COLORS.white },
  function: { fg: '#D2A8FF' },
  keyword: { bold: true, fg: '#FF7B72' },
  'markup.heading': { bold: true, fg: '#58A6FF' },
  'markup.heading.1': { bold: true, fg: COLORS.accent },
  'markup.heading.2': { bold: true, fg: COLORS.accent },
  'markup.heading.3': { bold: true, fg: '#CC7A5C' },
  'markup.list': { fg: '#FF7B72' },
  'markup.raw': { bg: '#333333', fg: COLORS.yellow },
  number: { fg: '#79C0FF' },
  operator: { fg: '#FF7B72' },
  property: { fg: '#79C0FF' },
  string: { fg: '#A5D6FF' },
  type: { fg: '#FFA657' },
  variable: { fg: '#FFA657' },
});

export const codeSyntaxStyle = SyntaxStyle.fromStyles({
  comment: { fg: '#8B949E' },
  constant: { fg: '#79C0FF' },
  default: { fg: '#C9D1D9' },
  function: { fg: '#D2A8FF' },
  keyword: { bold: true, fg: '#FF7B72' },
  number: { fg: '#79C0FF' },
  operator: { fg: '#FF7B72' },
  property: { fg: '#79C0FF' },
  string: { fg: '#A5D6FF' },
  type: { fg: '#FFA657' },
  variable: { fg: '#C9D1D9' },
});
